name: spriteframe_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - c-compiler=1.11.0=h528c1b4_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cccl=2.3.2=h84bb9a4_1
  - cuda-cccl=12.4.127=h57928b3_2
  - cuda-cccl_win-64=12.4.127=h57928b3_2
  - cuda-command-line-tools=12.4.1=h57928b3_1
  - cuda-compiler=12.4.1=h63438b5_0
  - cuda-crt-dev_win-64=12.4.131=h57928b3_1
  - cuda-crt-tools=12.4.131=h57928b3_1
  - cuda-cudart=12.4.127=he0c23c2_2
  - cuda-cudart-dev=12.4.127=he0c23c2_2
  - cuda-cudart-dev_win-64=12.4.127=he0c23c2_2
  - cuda-cudart-static=12.4.127=he0c23c2_2
  - cuda-cudart-static_win-64=12.4.127=he0c23c2_2
  - cuda-cudart_win-64=12.4.127=he0c23c2_2
  - cuda-cuobjdump=12.4.127=he0c23c2_2
  - cuda-cupti=12.4.127=he0c23c2_2
  - cuda-cupti-dev=12.4.127=he0c23c2_2
  - cuda-cuxxfilt=12.4.127=he0c23c2_2
  - cuda-libraries=12.4.1=h57928b3_1
  - cuda-libraries-dev=12.4.1=h57928b3_1
  - cuda-nvcc=12.4.131=h8f04d04_1
  - cuda-nvcc-dev_win-64=12.4.131=h57928b3_1
  - cuda-nvcc-impl=12.4.131=h7e770fd_1
  - cuda-nvcc-tools=12.4.131=h63175ca_1
  - cuda-nvcc_win-64=12.4.131=h8f04d04_1
  - cuda-nvdisasm=12.4.127=he0c23c2_2
  - cuda-nvml-dev=12.4.127=he0c23c2_2
  - cuda-nvprof=12.4.127=he0c23c2_2
  - cuda-nvprune=12.4.127=he0c23c2_2
  - cuda-nvrtc=12.4.127=he0c23c2_2
  - cuda-nvrtc-dev=12.4.127=he0c23c2_2
  - cuda-nvvm-dev_win-64=12.4.131=h57928b3_1
  - cuda-nvvm-impl=12.4.131=h63175ca_1
  - cuda-nvvm-tools=12.4.131=h63175ca_1
  - cuda-nvvp=12.4.127=he0c23c2_2
  - cuda-opencl=12.4.127=he0c23c2_1
  - cuda-opencl-dev=12.4.127=he0c23c2_1
  - cuda-profiler-api=12.4.127=h57928b3_2
  - cuda-sanitizer-api=12.4.127=he0c23c2_2
  - cuda-toolkit=12.4.1=h7428d3b_0
  - cuda-tools=12.4.1=h57928b3_1
  - cuda-version=12.4=h3060b56_3
  - cuda-visual-tools=12.4.1=h57928b3_1
  - cudnn=9.10.2.21=h32ff316_0
  - cxx-compiler=1.11.0=h1c1089f_0
  - expat=2.7.3=h885b0b7_4
  - fontconfig=2.15.0=h765892d_1
  - freetype=2.14.1=h57928b3_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - krb5=1.21.3=hdf4eb48_0
  - libcublas=12.4.5.8=he0c23c2_2
  - libcublas-dev=12.4.5.8=he0c23c2_2
  - libcudnn=9.10.2.21=hca898b4_0
  - libcudnn-dev=9.10.2.21=hca898b4_0
  - libcufft=11.2.1.3=he0c23c2_2
  - libcufft-dev=11.2.1.3=he0c23c2_2
  - libcurand=10.3.5.147=he0c23c2_2
  - libcurand-dev=10.3.5.147=he0c23c2_2
  - libcusolver=11.6.1.9=he0c23c2_2
  - libcusolver-dev=11.6.1.9=he0c23c2_2
  - libcusparse=12.3.1.170=he0c23c2_2
  - libcusparse-dev=12.3.1.170=he0c23c2_2
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.0=h7025463_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libnpp=12.2.5.30=he0c23c2_2
  - libnpp-dev=12.2.5.30=he0c23c2_2
  - libnvfatbin=12.4.127=he0c23c2_2
  - libnvfatbin-dev=12.4.127=he0c23c2_2
  - libnvjitlink=12.4.127=he0c23c2_2
  - libnvjitlink-dev=12.4.127=he0c23c2_2
  - libnvjpeg=12.3.1.117=he0c23c2_2
  - libnvjpeg-dev=12.3.1.117=h57928b3_2
  - libpng=1.6.54=h7351971_0
  - libxcb=1.15=hcd874cb_0
  - libzlib=1.3.1=h02ab6af_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - msys2-conda-epoch=20160418=1
  - opencl-headers=2025.06.13=he0c23c2_0
  - openssl=3.6.0=h725018a_0
  - pcre2=10.44=h99c9b8b_2
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.4=hcd874cb_1001
  - python=3.9.25=h716150d_1
  - setuptools=80.9.0=py39haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pytorch=2.5.1=py3.9_cuda12.4_cudnn9_0
  - torchvision=0.20.1=py39_cu124
  - torchaudio=2.5.1=py39_cu124
  - pytorch-cuda=12.4
  - certifi
  - cffi
  - charset-normalizer
  - filelock
  - idna
  - numpy=1.26.4
  - pillow
  - pycparser
  - requests
  - sympy=1.13.1
  - typing_extensions
  - urllib3
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - attrs==25.4.0
      - click==8.1.8
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.2.4
      - flatbuffers==25.12.19
      - fonttools==4.60.2
      - fsspec==2024.10.0
      - humanfriendly==10.0
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mediapipe==0.10.8
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.60.0
      - onnxruntime-gpu==1.19.2
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.8.1.78
      - packaging==24.2
      - platformdirs==4.4.0
      - pooch==1.8.2
      - protobuf==3.20.3
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pymatting==1.1.14
      - pyparsing==3.3.2
      - pyreadline3==3.5.4
      - pyside6==6.6.1
      - pyside6-addons==6.6.1
      - pyside6-essentials==6.6.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2026.1.15
      - rembg==2.0.52
      - rpds-py==0.27.1
      - scikit-image==0.24.0
      - scipy==1.13.1
      - shiboken6==6.6.1
      - six==1.17.0
      - tifffile==2024.8.30
      - tqdm==4.65.2
      - zipp==3.23.0
